baseURL = "http://www.linuxlefty.com/"
languageCode = "en-us"
title = "LinuxLefty"
theme = "LinuxLefty-Theme"
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]

author = "Peter Naudus"
related_content_limit = 5
description = "The personal website of Peter Naudus (aka LinuxLefty)"

[related]
threshold = 1
includeNewer = true
toLower = true

[[related.indices]]
name = "keywords"
weight = 150

[[related.indices]]
name = "categories"
weight = 30

[[related.indices]]
name = "tags"
weight = 100

[params.seo]
disable_bpg = true # Disable BPG image support

[[menu.main]]
name = "Home"
weight = 1
identifier = "home"
url = "/"

[[menu.main]]
name = "Blog"
weight = 2
identifier = "blog"
url = "/posts"

[[menu.main]]
name = "Resume"
weight = 3
identifier = "resume"
url = "/resume"
